services:
  fk-ollama:
    build: ./fk-ollama
    restart: unless-stopped
    environment:
      #- OLLAMA_HOST=http://ollama:11434  # Connect to the already running Ollama container
      - OLLAMA_HOST=http://host.docker.internal:11434
    expose:
      - "3002"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - fk-ollama
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs

networks:
  app_network:
    driver: bridge